export const ordersSample = [
  {
    BuyerInfo: {
      BuyerEmail: 'bwl39lsqkbxfv7v@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-5711987-2934627',
    EarliestShipDate: '2023-01-31T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-31T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-30T19:40:50Z',
    ShippingAddress: {
      StateOrRegion: 'Ontario',
      PostalCode: 'L7M 0H3',
      City: 'Burlington',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-5711987-2934627',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '225.99',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T04:58:15Z',
    ShipmentServiceLevelCategory: 'Expedited',
    ShippingAddressGeoLocation: {
      latitude: 43.4088895,
      longitude: -79.816192,
    },
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '26.00',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '199.99',
        },
        ASIN: 'B09ZVNL3JC',
        SellerSKU: 'magic_train',
        Title:
          'Magic Model Train Set - 2000+ PCS Remote Control Train Toy w/ Tracks, Sound & Light - Christmas Tree Train',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72674013033801',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
  },
  {
    BuyerInfo: {
      BuyerEmail: 'j72mqmbfxgxybnm@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-4212943-5016201',
    EarliestShipDate: '2023-01-31T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-31T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-30T11:51:58Z',
    ShippingAddress: {
      StateOrRegion: 'ON',
      PostalCode: 'L6R2H1',
      City: 'Brampton',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-4212943-5016201',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '33.89',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-30T21:18:24Z',
    ShipmentServiceLevelCategory: 'Expedited',
    ShippingAddressGeoLocation: {
      latitude: 43.7324111,
      longitude: -79.7604903,
    },
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '3.90',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '29.99',
        },
        ASIN: 'B09LZ5BSJN',
        SellerSKU: 'train_tracks',
        Title: 'Krenzo Train Tracks (23 Pieces)',
        ShippingTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsGift: 'false',
        ShippingPrice: {
          CurrencyCode: 'CAD',
          Amount: '3.39',
        },
        ShippingDiscount: {
          CurrencyCode: 'CAD',
          Amount: '3.39',
        },
        ShippingDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72636976287001',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
  },
  {
    BuyerInfo: {
      BuyerEmail: 'zr93hh3qkfs54pk@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-1816367-5872203',
    EarliestShipDate: '2023-01-31T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-31T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-29T17:28:05Z',
    ShippingAddress: {
      StateOrRegion: 'British Columbia',
      PostalCode: 'V3R 8Z9',
      City: 'Surrey',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-1816367-5872203',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '100.74',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-30T16:52:20Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '10.79',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '89.95',
        },
        ASIN: 'B097TJG9QL',
        SellerSKU: 'Green_Car_App',
        Title:
          'RC Tank APP Contrcol RC STEM Building Block - 400+ PCS RC Car Kit Technic - Perfect Educational Boys Toys Gift - Remote Control Cars for Kids',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72637576231761',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 49.1671407,
      longitude: -122.7912606,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: '6nj8l0f7hf46nsc@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-9636229-0289847',
    EarliestShipDate: '2023-01-30T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-29T17:16:00Z',
    ShippingAddress: {
      StateOrRegion: 'British Columbia',
      PostalCode: 'V3V 6J8',
      City: 'Surrey',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-9636229-0289847',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '87.30',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-30T02:17:50Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '9.35',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '77.95',
        },
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids for Holidays Around Christmas Tree with Tracks, High Speed Bullet Engine on Railroad with Sound & Light, Experience Polar',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72633853623561',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 49.1689301,
      longitude: -122.881839,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'kbr71gvx9v649fb@marketplace.amazon.com',
    },
    AmazonOrderId: '111-9983681-0573801',
    EarliestShipDate: '2023-01-30T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 2,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-28T20:14:46Z',
    ShippingAddress: {
      StateOrRegion: 'WA',
      PostalCode: '99301-8762',
      City: 'PASCO',
      CountryCode: 'US',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '111-9983681-0573801',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'USD',
      Amount: '129.62',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T17:36:26Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        TaxCollection: {
          Model: 'MarketplaceFacilitator',
          ResponsibleParty: 'Amazon Services, Inc.',
        },
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'USD',
          Amount: '9.72',
        },
        QuantityShipped: 2,
        ItemPrice: {
          CurrencyCode: 'USD',
          Amount: '119.90',
        },
        ASIN: 'B07HKGX4V6',
        SellerSKU: 'Green_Tank',
        Title:
          'Qmecha 5 in 1 Remote Control STEM Building Blocks Car Tank - 400+ PCS RC Car Kit - Perfect Educational Toy Gift',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 2,
        PromotionDiscountTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        OrderItemId: '72608385458561',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 46.2305049,
      longitude: -119.0922316,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'j9hrr4m278lj479@marketplace.amazon.ca',
    },
    AmazonOrderId: '701-2540472-3036236',
    EarliestShipDate: '2023-01-30T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-28T11:50:06Z',
    ShippingAddress: {
      StateOrRegion: 'BC',
      PostalCode: 'V4N 1R5',
      City: 'Surrey',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '701-2540472-3036236',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '86.02',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T22:38:17Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '9.22',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '76.80',
        },
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72548129152241',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 49.2071744,
      longitude: -122.7797653,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'c8lrlby0y33qr1t@marketplace.amazon.ca',
    },
    AmazonOrderId: '701-2222705-8896206',
    EarliestShipDate: '2023-01-28T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-28T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-28T02:17:28Z',
    ShippingAddress: {
      StateOrRegion: 'Quebec',
      PostalCode: 'J6J 1Y7',
      City: 'Chateauguay',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '701-2222705-8896206',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '137.96',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-28T06:05:39Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '17.97',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '119.99',
        },
        ASIN: 'B09ZWH3HK2',
        SellerSKU: 'glow_track',
        Title:
          'Magic Race Car Track for Kids - 300+ PCs Flexible Glow Tracks Racing Set',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72506221929321',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 45.3675915,
      longitude: -73.7339835,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'z2nbdz9tdnlt333@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-7570956-3629012',
    EarliestShipDate: '2023-01-29T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-29T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-28T00:31:08Z',
    ShippingAddress: {
      StateOrRegion: 'Qc',
      PostalCode: 'J6X2V7',
      City: 'Terrebonne',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-7570956-3629012',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '20.64',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T01:46:45Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '2.69',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '17.95',
        },
        ASIN: 'B08XNVD54R',
        SellerSKU: 'flying_ball',
        Title:
          'Flying Ball Mini Drone - Hand Operated The Hover Ball 2022 - Nebula Flying Orb Ball',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72518168950281',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 45.7195754,
      longitude: -73.66440469999999,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'jrthzfb3dpp0h20@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-4535843-9693015',
    EarliestShipDate: '2023-01-29T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-29T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-27T22:57:33Z',
    ShippingAddress: {
      StateOrRegion: 'AB',
      PostalCode: 'T3H 5V4',
      City: 'Calgary',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-4535843-9693015',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '18.85',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T01:49:04Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '0.90',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '17.95',
        },
        ASIN: 'B08XNVD54R',
        SellerSKU: 'flying_ball',
        Title:
          'Flying Ball Mini Drone - Hand Operated The Hover Ball 2022 - Nebula Flying Orb Ball',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72505208006201',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 51.0419859,
      longitude: -114.1949364,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 's39wr4vrw86zygy@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-5668604-7005005',
    EarliestShipDate: '2023-01-28T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-28T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-27T22:17:51Z',
    ShippingAddress: {
      StateOrRegion: 'Manitoba',
      PostalCode: 'R2W 1W2',
      City: 'Winnipeg',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-5668604-7005005',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '86.02',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T05:07:00Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '9.22',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '76.80',
        },
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72504976550241',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 49.9208599,
      longitude: -97.1444396,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: '75kpmzzk2r0b52d@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-9863063-7124217',
    EarliestShipDate: '2023-01-28T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-28T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-27T17:42:49Z',
    ShippingAddress: {
      StateOrRegion: 'Ontario',
      PostalCode: 'L2J0A3',
      City: 'Niagara Falls',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-9863063-7124217',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '101.64',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T21:02:24Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '11.69',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '89.95',
        },
        ASIN: 'B097TJG9QL',
        SellerSKU: 'Green_Car_App',
        Title:
          'RC Tank APP Contrcol RC STEM Building Block - 400+ PCS RC Car Kit Technic - Perfect Educational Boys Toys Gift - Remote Control Cars for Kids',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72503652511441',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 43.1397311,
      longitude: -79.08604150000001,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'pj1btwlwwvlh586@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-5825424-4687429',
    EarliestShipDate: '2023-01-28T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-28T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-27T17:23:44Z',
    ShippingAddress: {
      StateOrRegion: 'Alberta',
      PostalCode: 'T2P 2B3',
      City: 'Calgary',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-5825424-4687429',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '18.85',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-28T01:50:08Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '0.90',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '17.95',
        },
        ASIN: 'B08XNVD54R',
        SellerSKU: 'flying_ball',
        Title:
          'Flying Ball Mini Drone - Hand Operated The Hover Ball 2022 - Nebula Flying Orb Ball',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72487474369081',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 51.0476793,
      longitude: -114.0834345,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'prjzd0fg6ftsnng@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-0866159-5315464',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-27T03:16:06Z',
    ShippingAddress: {
      StateOrRegion: 'ON',
      PostalCode: 'N1E 7J9',
      City: 'Guelph',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-0866159-5315464',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '88.08',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T11:32:33Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '10.13',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '77.95',
        },
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids for Holidays Around Christmas Tree with Tracks, High Speed Bullet Engine on Railroad with Sound & Light, Experience Polar',
        ShippingTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsGift: 'false',
        ShippingPrice: {
          CurrencyCode: 'CAD',
          Amount: '3.93',
        },
        ShippingDiscount: {
          CurrencyCode: 'CAD',
          Amount: '3.93',
        },
        ShippingDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionIds: ['CA Core Free Shipping - A1MKTV4OYO2HJ1'],
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72482666439201',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 43.5673127,
      longitude: -80.2152255,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'j7smlgq1jzynpxw@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-6155330-9224247',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-26T23:42:36Z',
    ShippingAddress: {
      StateOrRegion: 'Ontario',
      PostalCode: 'M6P 1J7',
      City: 'Toronto',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-6155330-9224247',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '20.28',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T02:56:43Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '2.33',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '17.95',
        },
        ASIN: 'B08XNVD54R',
        SellerSKU: 'flying_ball',
        Title:
          'Flying Ball Mini Drone - Hand Operated The Hover Ball 2022 - Nebula Flying Orb Ball',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72478237416601',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 43.6629316,
      longitude: -79.4582588,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'dtkpvmbvz51q096@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-8128570-0382602',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-26T21:08:33Z',
    ShippingAddress: {
      StateOrRegion: 'Alberta',
      PostalCode: 'T3K 2N7',
      City: 'Calgary',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-8128570-0382602',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '81.85',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T04:47:56Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '3.90',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '77.95',
        },
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids for Holidays Around Christmas Tree with Tracks, High Speed Bullet Engine on Railroad with Sound & Light, Experience Polar',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72474207616801',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 51.04473309999999,
      longitude: -114.0718831,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'bfttxlxwmnzcpd4@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-6027845-6391400',
    EarliestShipDate: '2023-01-28T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-28T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-26T19:59:17Z',
    ShippingAddress: {
      StateOrRegion: 'quebec',
      PostalCode: 'G0L1Z0',
      City: 'Packington',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-6027845-6391400',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '88.30',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T18:57:33Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '11.50',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '76.80',
        },
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        ShippingTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsGift: 'false',
        ShippingPrice: {
          CurrencyCode: 'CAD',
          Amount: '3.27',
        },
        ShippingDiscount: {
          CurrencyCode: 'CAD',
          Amount: '3.27',
        },
        ShippingDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionIds: ['CA Core Free Shipping - A1MKTV4OYO2HJ1'],
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72475447172881',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 47.4897484,
      longitude: -68.78576420000002,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: '06g18dcbgwpbnh8@marketplace.amazon.com',
    },
    AmazonOrderId: '112-0623223-3725851',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-26T17:15:40Z',
    ShippingAddress: {
      StateOrRegion: 'OH',
      PostalCode: '44131-2100',
      City: 'INDEPENDENCE',
      CountryCode: 'US',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '112-0623223-3725851',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'USD',
      Amount: '113.18',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T14:10:39Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        TaxCollection: {
          Model: 'MarketplaceFacilitator',
          ResponsibleParty: 'Amazon Services, Inc.',
        },
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'USD',
          Amount: '8.38',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'USD',
          Amount: '104.80',
        },
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids - High Speed Bullet Train with Tracks, Sound & Light, Experience Polar Express with Many Accessories and Multiple Paths',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        OrderItemId: '72471315284001',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 41.3884635,
      longitude: -81.65829939999999,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 's46llscx47394c5@marketplace.amazon.ca',
    },
    AmazonOrderId: '702-0379775-7376208',
    EarliestShipDate: '2023-01-30T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-26T15:51:28Z',
    ShippingAddress: {
      StateOrRegion: 'Nova Scotia',
      PostalCode: 'B0E 1A0',
      City: 'Arichat',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '702-0379775-7376208',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '103.49',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T19:35:01Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '13.50',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '89.99',
        },
        ASIN: 'B07HKGX4V6',
        SellerSKU: 'green_tank',
        Title:
          '5 in 1 Remote Control STEM Building Blocks Car Tank - 400+ PCS RC Car Kit - Kids Toys Age 6-12 - Perfect Educational Toy Gift for Kids',
        ShippingTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsGift: 'false',
        ShippingPrice: {
          CurrencyCode: 'CAD',
          Amount: '2.51',
        },
        ShippingDiscount: {
          CurrencyCode: 'CAD',
          Amount: '2.51',
        },
        ShippingDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionIds: ['CA Core Free Shipping - A1MKTV4OYO2HJ1'],
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72468283575041',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 45.5137315,
      longitude: -61.01184250000001,
    },
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '701-3762852-8541836',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-26T01:17:49Z',
    ShippingAddress: {
      StateOrRegion: 'British Columbia',
      PostalCode: 'V5K 3E9',
      City: 'Vancouver',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '701-3762852-8541836',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '39.19',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-26T11:28:26Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '4.20',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '34.99',
        },
        ASIN: 'B09ZVQN8W1',
        SellerSKU: 'mini_dino_track',
        Title:
          'Jurassic Dinosaur Toy Race Track - 100+ PCs Dinosaur Toys for 3 Year Old Boys and Up - Great Christmas Toy Gift for Kids',
        IsGift: 'true',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72395539178121',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 49.2725259,
      longitude: -123.0376496,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: '8ggbzsbxq6m7bn1@marketplace.amazon.ca',
    },
    AmazonOrderId: '701-8224970-4665056',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-26T00:03:51Z',
    ShippingAddress: {
      StateOrRegion: 'BC',
      PostalCode: 'V4W 1L4',
      City: 'Aldergrove',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '701-8224970-4665056',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '87.30',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-26T11:31:50Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '9.35',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '77.95',
        },
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids for Holidays Around Christmas Tree with Tracks, High Speed Bullet Engine on Railroad with Sound & Light, Experience Polar',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72393017141201',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 49.1119127,
      longitude: -122.4998712,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'jsnpftst84v5j60@marketplace.amazon.com',
    },
    AmazonOrderId: '112-8281138-9103418',
    EarliestShipDate: '2023-01-26T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-26T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-25T20:07:12Z',
    ShippingAddress: {
      StateOrRegion: 'NY',
      PostalCode: '11435-4402',
      City: 'JAMAICA',
      CountryCode: 'US',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '112-8281138-9103418',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'USD',
      Amount: '65.27',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-28T23:43:38Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        TaxCollection: {
          Model: 'MarketplaceFacilitator',
          ResponsibleParty: 'Amazon Services, Inc.',
        },
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'USD',
          Amount: '5.32',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'USD',
          Amount: '59.95',
        },
        ASIN: 'B07HKGX4V6',
        SellerSKU: 'Green_Tank',
        Title:
          'Qmecha 5 in 1 Remote Control STEM Building Blocks Car Tank - 400+ PCS RC Car Kit - Perfect Educational Toy Gift',
        ShippingTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        IsGift: 'false',
        ShippingPrice: {
          CurrencyCode: 'USD',
          Amount: '7.95',
        },
        ShippingDiscount: {
          CurrencyCode: 'USD',
          Amount: '7.95',
        },
        ShippingDiscountTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        PromotionIds: ['US Core Free Shipping Promotion A3JU1FCINF5SD0'],
        PromotionDiscount: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        OrderItemId: '72360907038921',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 40.702677,
      longitude: -73.7889689,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'wt84zktm88673fq@marketplace.amazon.ca',
    },
    AmazonOrderId: '701-1094089-4393000',
    EarliestShipDate: '2023-01-26T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-26T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-25T19:34:33Z',
    ShippingAddress: {
      StateOrRegion: 'QC',
      PostalCode: 'J5R 0P7',
      City: 'La Prairie',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '701-1094089-4393000',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '80.47',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T11:56:26Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '10.48',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '69.99',
        },
        ASIN: 'B07VXYMN4Z',
        SellerSKU: 'Red_Car',
        Title:
          '16 in 1 Remote Control STEM Technic Building Blocks Robot Toy for Kids - 458 PCS RC Car for Kids - Perfect Educational Toy Gift for Kids',
        ShippingTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsGift: 'false',
        ShippingPrice: {
          CurrencyCode: 'CAD',
          Amount: '2.44',
        },
        ShippingDiscount: {
          CurrencyCode: 'CAD',
          Amount: '2.44',
        },
        ShippingDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionIds: ['CA Core Free Shipping - A1MKTV4OYO2HJ1'],
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72376528445801',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 45.3981407,
      longitude: -73.4935323,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'm4ylzlvwqv1r95b@marketplace.amazon.com',
    },
    AmazonOrderId: '113-9376596-5275454',
    EarliestShipDate: '2023-01-27T07:59:59Z',
    ReplacedOrderId: '114-2499193-5826603',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'true',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-27T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-25T17:46:27Z',
    ShippingAddress: {
      StateOrRegion: 'CA',
      PostalCode: '95037-9180',
      City: 'MORGAN HILL',
      CountryCode: 'US',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '113-9376596-5275454',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-26T17:01:47Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        TaxCollection: {
          Model: 'MarketplaceFacilitator',
          ResponsibleParty: 'Amazon Services, Inc.',
        },
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 1,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B07VXYMN4Z',
        SellerSKU: 'Red_Car',
        Title:
          '16 in 1 Remote Control STEM Building Blocks RC Robot - 458 PCS RC Car Kit - Kids Toys Age 6-12 - Perfect Educational Toy Gift for Kids',
        OrderItemId: '72371790167281',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 37.1305012,
      longitude: -121.6543901,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'pxbwz6sn0c4cshs@marketplace.amazon.com',
    },
    AmazonOrderId: '111-6555073-6000245',
    EarliestShipDate: '2023-01-26T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-26T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-25T14:14:37Z',
    ShippingAddress: {
      StateOrRegion: 'OH',
      PostalCode: '43123-8398',
      City: 'GROVE CITY',
      CountryCode: 'US',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '111-6555073-6000245',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'USD',
      Amount: '110.67',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-25T21:21:17Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        TaxCollection: {
          Model: 'MarketplaceFacilitator',
          ResponsibleParty: 'Amazon Services, Inc.',
        },
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'USD',
          Amount: '7.72',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'USD',
          Amount: '102.95',
        },
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        OrderItemId: '72370826394441',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 39.88145189999999,
      longitude: -83.0929644,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: '18dkqr0dm01pqws@marketplace.amazon.com',
    },
    AmazonOrderId: '113-7510068-5869029',
    EarliestShipDate: '2023-01-26T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-26T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-25T14:05:17Z',
    ShippingAddress: {
      StateOrRegion: 'SC',
      PostalCode: '29631-1216',
      City: 'CLEMSON',
      CountryCode: 'US',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '113-7510068-5869029',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'USD',
      Amount: '64.15',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-26T04:24:02Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        TaxCollection: {
          Model: 'MarketplaceFacilitator',
          ResponsibleParty: 'Amazon Services, Inc.',
        },
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'USD',
          Amount: '4.20',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'USD',
          Amount: '59.95',
        },
        ASIN: 'B07HKGX4V6',
        SellerSKU: 'Green_Tank',
        Title:
          'Qmecha 5 in 1 Remote Control STEM Building Blocks Car Tank - 400+ PCS RC Car Kit - Perfect Educational Toy Gift',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'USD',
          Amount: '0.00',
        },
        OrderItemId: '72369111184761',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 34.6790356,
      longitude: -82.82636149999999,
    },
  },
  {
    BuyerInfo: {
      BuyerEmail: 'hlp7hfscm5vjzz0@marketplace.amazon.ca',
    },
    AmazonOrderId: '701-4108844-1578620',
    EarliestShipDate: '2023-01-26T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Shipped',
    NumberOfItemsShipped: 1,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-26T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-25T06:23:59Z',
    ShippingAddress: {
      StateOrRegion: 'British Columbia',
      PostalCode: 'V1J 0N2',
      City: 'Fort St. John',
      CountryCode: 'CA',
    },
    IsAccessPointOrder: false,
    SellerOrderId: '701-4108844-1578620',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '100.74',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-25T17:50:15Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '10.79',
        },
        QuantityShipped: 1,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '89.95',
        },
        ASIN: 'B097TJG9QL',
        SellerSKU: 'Green_Car_App',
        Title:
          'RC Tank APP Contrcol RC STEM Building Block - 400+ PCS RC Car Kit Technic - Perfect Educational Boys Toys Gift - Remote Control Cars for Kids',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72364420162201',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
    ShippingAddressGeoLocation: {
      latitude: 56.2483601,
      longitude: -120.8619769,
    },
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '702-3173368-8075423',
    EarliestShipDate: '2023-02-01T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-01T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-31T19:13:28Z',
    IsAccessPointOrder: false,
    SellerOrderId: '702-3173368-8075423',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T19:13:33Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B09ZVQN8W1',
        SellerSKU: 'mini_dino_track',
        Title:
          'Jurassic Dinosaur Toy Race Track - 100+ PCs Dinosaur Toys for 3 Year Old Boys and Up - Great Christmas Toy Gift for Kids',
        OrderItemId: '72747675387281',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '702-3876570-1101817',
    EarliestShipDate: '2023-02-01T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-01T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-31T18:27:26Z',
    IsAccessPointOrder: false,
    SellerOrderId: '702-3876570-1101817',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T18:27:33Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B09ZVQN8W1',
        SellerSKU: 'mini_dino_track',
        Title:
          'Jurassic Dinosaur Toy Race Track - 100+ PCs Dinosaur Toys for 3 Year Old Boys and Up - Great Christmas Toy Gift for Kids',
        OrderItemId: '72743796752361',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '702-4786338-3419408',
    EarliestShipDate: '2023-02-02T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-02T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-31T05:18:59Z',
    IsAccessPointOrder: false,
    SellerOrderId: '702-4786338-3419408',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T17:46:24Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B08XNVD54R',
        SellerSKU: 'flying_ball',
        Title:
          'Flying Ball Mini Drone - Hand Operated The Hover Ball 2022 - Nebula Flying Orb Ball',
        OrderItemId: '72700319529321',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '702-4800530-4798608',
    EarliestShipDate: '2023-01-31T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-31T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-31T03:59:20Z',
    IsAccessPointOrder: false,
    SellerOrderId: '702-4800530-4798608',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T03:59:24Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B08XNVD54R',
        SellerSKU: 'flying_ball',
        Title:
          'Flying Ball Mini Drone - Hand Operated The Hover Ball 2022 - Nebula Flying Orb Ball',
        OrderItemId: '72698499731801',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '112-6444545-0955401',
    EarliestShipDate: '2023-01-31T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-31T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-30T21:37:16Z',
    IsAccessPointOrder: false,
    SellerOrderId: '112-6444545-0955401',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-30T21:37:25Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B09ZVNL3JC',
        SellerSKU: 'magic_train',
        Title:
          'Magic Model Train Set - 2000+ PCS Remote Control Train Toy w/ Tracks, Sound & Light',
        PromotionIds: ['US Core Free Shipping Promotion A3JU1FCINF5SD0'],
        OrderItemId: '72667796925641',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '701-5111315-5145047',
    EarliestShipDate: '2023-01-30T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-29T19:26:25Z',
    IsAccessPointOrder: false,
    SellerOrderId: '701-5111315-5145047',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T19:26:33Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids for Holidays Around Christmas Tree with Tracks, High Speed Bullet Engine on Railroad with Sound & Light, Experience Polar Express with Many Accessories and Multiple Paths',
        PromotionIds: ['CA Core Free Shipping - A1MKTV4OYO2HJ1'],
        OrderItemId: '72612951048081',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '702-9561421-4866661',
    EarliestShipDate: '2023-01-31T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-31T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-29T17:40:19Z',
    IsAccessPointOrder: false,
    SellerOrderId: '702-9561421-4866661',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T03:39:45Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids for Holidays Around Christmas Tree with Tracks, High Speed Bullet Engine on Railroad with Sound & Light, Experience Polar Express with Many Accessories and Multiple Paths',
        OrderItemId: '72640918473121',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '111-2305965-8526616',
    EarliestShipDate: '2023-02-03T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-03T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-29T01:54:24Z',
    IsAccessPointOrder: false,
    SellerOrderId: '111-2305965-8526616',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-30T02:17:05Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'true',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        OrderItemId: '72618802590961',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '701-9452365-8597850',
    EarliestShipDate: '2023-01-30T08:00:00Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T08:00:00Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-27T22:54:16Z',
    IsAccessPointOrder: false,
    SellerOrderId: '701-9452365-8597850',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    OrderTotal: {
      CurrencyCode: 'CAD',
      Amount: '80.47',
    },
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T14:47:50Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        BuyerInfo: {},
        ItemTax: {
          CurrencyCode: 'CAD',
          Amount: '10.48',
        },
        QuantityShipped: 0,
        ItemPrice: {
          CurrencyCode: 'CAD',
          Amount: '69.99',
        },
        ASIN: 'B07VXYMN4Z',
        SellerSKU: 'Red_Car',
        Title:
          '16 in 1 Remote Control STEM Technic Building Blocks Robot Toy for Kids - 458 PCS RC Car for Kids - Perfect Educational Toy Gift for Kids',
        IsGift: 'false',
        IsTransparency: false,
        QuantityOrdered: 1,
        PromotionDiscountTax: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        PromotionDiscount: {
          CurrencyCode: 'CAD',
          Amount: '0.00',
        },
        OrderItemId: '72512456585721',
        DeemedResellerCategory: 'CA_MPF',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '113-3637402-7253856',
    EarliestShipDate: '2023-02-02T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-02T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-27T16:39:35Z',
    IsAccessPointOrder: false,
    SellerOrderId: '113-3637402-7253856',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-27T16:39:42Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B08818K84M',
        SellerSKU: 'train_set_white',
        Title:
          'Electric Train Set for Kids - High Speed Bullet Train with Tracks, Sound & Light, Experience Polar Express with Many Accessories and Multiple Paths',
        OrderItemId: '72501574885201',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '114-3859090-4403425',
    EarliestShipDate: '2023-02-01T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-01T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-27T14:13:16Z',
    IsAccessPointOrder: false,
    SellerOrderId: '114-3859090-4403425',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-31T17:33:12Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        OrderItemId: '72498103602921',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '114-4336639-1002634',
    EarliestShipDate: '2023-01-30T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Pending',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 1,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-30T07:59:59Z',
    ShipServiceLevel: 'Expedited',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-25T19:00:35Z',
    IsAccessPointOrder: false,
    SellerOrderId: '114-4336639-1002634',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-29T16:11:14Z',
    ShipmentServiceLevelCategory: 'Expedited',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 1,
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        OrderItemId: '72380189984241',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '112-8176589-8241037',
    EarliestShipDate: '2023-02-02T07:59:59Z',
    SalesChannel: 'Amazon.com',
    OrderStatus: 'Canceled',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-02-02T07:59:59Z',
    ShipServiceLevel: 'Standard',
    IsISPU: false,
    MarketplaceId: 'ATVPDKIKX0DER',
    PurchaseDate: '2023-01-28T23:25:36Z',
    IsAccessPointOrder: false,
    SellerOrderId: '112-8176589-8241037',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-28T23:29:00Z',
    ShipmentServiceLevelCategory: 'Standard',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 0,
        ASIN: 'B09ZVLS7YD',
        SellerSKU: 'train_alloy',
        Title:
          'Electric Train Set for Kids - Train Toy with Tracks, Sounds & Light',
        OrderItemId: '72616407539441',
      },
    ],
  },
  {
    BuyerInfo: {},
    AmazonOrderId: '702-3505156-6942649',
    EarliestShipDate: '2023-01-28T07:59:59Z',
    SalesChannel: 'Amazon.ca',
    OrderStatus: 'Canceled',
    NumberOfItemsShipped: 0,
    OrderType: 'StandardOrder',
    IsPremiumOrder: false,
    IsPrime: false,
    FulfillmentChannel: 'AFN',
    NumberOfItemsUnshipped: 0,
    HasRegulatedItems: false,
    IsReplacementOrder: 'false',
    IsSoldByAB: false,
    LatestShipDate: '2023-01-28T07:59:59Z',
    ShipServiceLevel: 'SecondDay',
    IsISPU: false,
    MarketplaceId: 'A2EUQ1WTGCTBG2',
    PurchaseDate: '2023-01-25T17:28:55Z',
    IsAccessPointOrder: false,
    SellerOrderId: '702-3505156-6942649',
    PaymentMethod: 'Other',
    IsBusinessOrder: false,
    PaymentMethodDetails: ['Standard'],
    IsGlobalExpressEnabled: false,
    LastUpdateDate: '2023-01-25T17:29:42Z',
    ShipmentServiceLevelCategory: 'SecondDay',
    OrderItems: [
      {
        ProductInfo: {
          NumberOfItems: '1',
        },
        IsGift: 'false',
        BuyerInfo: {},
        QuantityShipped: 0,
        IsTransparency: false,
        QuantityOrdered: 0,
        ASIN: 'B09ZWH3HK2',
        SellerSKU: 'glow_track',
        Title:
          'Magic Race Car Track for Kids - 300+ PCs Flexible Glow Tracks Racing Set',
        OrderItemId: '72371699492521',
      },
    ],
  },
];

export const filterOptionsSample = {
  Green_Tank: {
    label: 'Green_Tank',
    value: 'Green_Tank',
    selected: false,
    count: 3,
  },
  train_alloy: {
    label: 'train_alloy',
    value: 'train_alloy',
    selected: false,
    count: 8,
  },
  Red_Car: {
    label: 'Red_Car',
    value: 'Red_Car',
    selected: false,
    count: 3,
  },
  Green_Car_App: {
    label: 'Green_Car_App',
    value: 'Green_Car_App',
    selected: false,
    count: 3,
  },
  glow_track: {
    label: 'glow_track',
    value: 'glow_track',
    selected: false,
    count: 2,
  },
  train_set_white: {
    label: 'train_set_white',
    value: 'train_set_white',
    selected: false,
    count: 8,
  },
  mini_dino_track: {
    label: 'mini_dino_track',
    value: 'mini_dino_track',
    selected: false,
    count: 3,
  },
  green_tank: {
    label: 'green_tank',
    value: 'green_tank',
    selected: false,
    count: 1,
  },
  flying_ball: {
    label: 'flying_ball',
    value: 'flying_ball',
    selected: false,
    count: 6,
  },
  magic_train: {
    label: 'magic_train',
    value: 'magic_train',
    selected: false,
    count: 2,
  },
  train_tracks: {
    label: 'train_tracks',
    value: 'train_tracks',
    selected: false,
    count: 1,
  },
};
